### ISSUE TITLE
CORS Error

### ISSUE THREAD

**Issue by gravenp** [Geo-Web-Project/browser#29]
**Describe the bug**
The Spatial Browser's calls to Ceramic from https://geoweb.app/ are being blocked due to the CORS policy. Need to reach out to Ceramic to have our URL added (or address a different underlying issue causing this).

  Access to XMLHttpRequest at 'https://g12-a-ceramic.3boxlabs.com/api/v0/streams' from origin 'https://geoweb.app' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.
  
  g12-a-ceramic.3boxlabs.com/api/v0/streams:1          Failed to load resource: net::ERR_FAILED
  
  Uncaught (in promise) TypeError: Network request failed
      at A.s.onerror (309-480d3215c5038db4.js:1:531902)

**Comment by codynhat** [comment]
This should be fixed.

**Comment by gravenp** [comment]
Yup! Looks good. Thanks @codynhat.
