### ISSUE TITLE
Replace js-ipfs DHT delegating with Reframe

### ISSUE THREAD

**Issue by codynhat** [Geo-Web-Project/browser#59]
In order to improve performance of fetching content from the IPFS network, we should update to use the new Reframe protocol from some Kubo IPFS node. See https://blog.ipfs.tech/state-of-ipfs-in-js/#support-fully-speced-delegated-routing-protocols-and-endpoints

We can either find some existing node (depending on performance guarantees) or use the existing node at geoweb.network.

**Comment by swarna1101** [comment]
#62
