### ISSUE TITLE
Development setup error

### ISSUE THREAD

**Issue by anasaijaz** [Geo-Web-Project/browser#65]
**Describe the bug**
Error while setting up the project in local
![image](https://user-images.githubusercontent.com/27632474/210150518-5c552b6f-b91a-497b-9f71-897454cf0433.png)

**To Reproduce**
1. npm install
2. npm run dev

**Comment by anasaijaz** [comment]
Fixed this error in PR #66 
Also updated setup instructions
![image](https://user-images.githubusercontent.com/27632474/210151097-003373f1-cf75-45e6-bd55-c8fb75a20991.png)

**Comment by gravenp** [comment]
Closed with https://github.com/Geo-Web-Project/browser/pull/66.

Thanks, @anasaijaz! We appreciate you jumping in with a PR like this! 

If you haven't yet, you should join our Discord (https://discord.com/invite/reXgPru7ck) and shoot @codynhat & me a message. We can start including you in our open contributor rewards (bounties, SourceCred, etc.) if you're interested in doing more with the project.

**Comment by anasaijaz** [comment]
Sure thank you I will join the discord!
